### ISSUE TITLE
When assigning versions to issues, also assign parent if subtask

### ISSUE THREAD

**Issue by dazinator** [CatenaLogic/JiraCli#12]
### Feature description

We get the list of jira issues to assign to a version, by querying the commit log.
Often developers will have worked on a subtask, and will put the subtask issue id in the commit message.
When versions are assigned to subtasks - the subtask shows up, but the parent task does not get assigned / included in the release.
Often having a subtask appear on a release, isn't as useful as having the parent task - which provides much of the context.

I'm wondering whether it makes sense to automatically detect issues that are child issues (i.e subtasks) and also assign the parent task to the version.. What do you think?

**Comment by GeertvanHorrik** [comment]
Hmmm, this might sound interesting. Although this sounds like something jira should do automatically, I agree that we can do it in this tool as well. The only issue I see is that if there are multiple subtasks and they all point to a different version, it's going to be tricky. On the other hand, the tool should use the max versions since that is the one that really implements the full parent feature.

**Comment by dazinator** [comment]
> The only issue I see is that if there are multiple subtasks and they all point to a different version, it's going to be tricky. On the other hand, the tool should use the max versions since that is the one that really implements the full parent feature.

At the moment, if there are multiple versions, say 1.0.0-alpha1 and 1.0.0-alpha2 - you end up with all of those versions listed in the fixVersions field. I don't have a problem with this, becuase when you release a stable release, those versions are all merged into a stable version number, at which point you end up with "1.0.0" in the fixVersions field instead of the unstable ones.

We don't have beta or feature branches, so I am not sure how the merging works in those scenarios.

Would this work for you?

**Comment by GeertvanHorrik** [comment]
Hmmm, that seems to work well. We also automatically create release notes between versions (we have a service for this that we can query). Once we release a stable version, we merge all unstable / alpha / beta versions into the main version, but I think this could work.

**Comment by dazinator** [comment]
Just to continue on this now that its merged, I wondered if you also create jira versions for feature branches, ans whether you have an automated way to delete those jira versions once the feature branch has been closed / deleted?  At the moment, we allow build process to create the version for the feature and issues are assigned. Later once the feature is integrated and those commits are built on the develop branch, then those same jira issues get assigned an alpha version in jira as you'd expect - however the feature branch version gets left there. It would be ideal if the feature version could be removed once it was integrated - what do you think?

**Comment by GeertvanHorrik** [comment]
We don't release feature branches for our apps. They are mostly changes that are not ready to be merged (WIP), and once merged, we will ship them to alpha testers.

I am happy to remove these versions once integrated, but not sure what the versioning logic is for feature branches and how they can be combined with unique numbers using GitVersion.
