### ISSUE TITLE
Merging releases

### ISSUE THREAD

**Issue by dazinator** [CatenaLogic/JiraCli#9]
I just hit an issue, thought I'd discuss it.

For merging versions - the tests show we only merge versions that are unstable into the stable version of the same version number.

E.G as per the test:

```
        [TestCase]
        public async Task ReleaseVersionsThatShouldBeMerged()
        {
            var actionManager = ResolveService<IActionManager>();

            var action = actionManager.GetAction("CreateAndReleaseVersion");

            var createV1Context = CreateContext("2.0.0-unstable42");
            Assert.IsTrue(await action.Execute(createV1Context));

            var createV2Context = CreateContext("2.0.0-unstable48");
            Assert.IsTrue(await action.Execute(createV2Context));

            var createV3Context = CreateContext("2.0.0-unstable56");
            Assert.IsTrue(await action.Execute(createV3Context));

            var createStableVersionContext = CreateContext("2.0.0");
            Assert.IsTrue(await action.Execute(createStableVersionContext));
        }

```

That will merge all `2.0.0-instableX` into stable version `2.0.0`.

For my use case (which I believe is quite a common one), we start out with version `0.0.1-unstableX` version, and for our very first release we bump the version to `1.0.0`. In that circumstance we would still expect all previous unstable versions (0.X.Y-unstableZ) to be merged into the first stable release, but because of the bump this tool misses this. For subsequent versions the tool works fine.

Do you think the tool should be extended to cater for this scenario, basically special casing a `1.0.0` by allowing all prior `0.X.Y-unstable` versions to be merged into it?

**Comment by GeertvanHorrik** [comment]
Not sure about this. A lot of users release a 0.1, 0.2, 0.3 etc first. If you want your versions to start at 1.0.0, why don't you just set the initial version using GitVersion to 1.0.0? That sounds like a more viable option, otherwise this will prevent users to release 0.\* versions of their products (and since this is something we can't undo in Jira, I can imagine these users becoming furious if all their previous releases before 1.0 are being merged into 1.0).

**Comment by dazinator** [comment]
Yeah good point :-)

I think our team do want to follow semver and start with 0.X.Y during development whilst things are not stable, then bump to 1.0.0 when the release is now considered stable.

I think this issue is just about dealing with merging, when bumping version numbers in general. For example, suppose at some point after 1.0.0 we make some minor commits to produce `1.0.1-unstable0001` and `1.0.1-unstable0002`

Now suppose the third commit is a breaking change and the developer bumps the version to major version 2. So we end up with these builds / versions:
- `1.0.1-unstable0001`
- `1.0.1-unstable0002`
- `2.0.0-unstable0001`

When we merge to master, we will get a new stable build:
- `2.0.0`

That's the point where we (myself!) want to merge all previous unstable versions between the last stable release and the current stable release. At the moment, this won't work.

So how about this.. We extend the CLI to take an optional extra argument when merging versions. This argument would be a `FromVersion`. When building master, you could pass that argument is as the Previous stable version of master (for example `1.0.0`) and then the tool will merge all unstable versions between that range (i.e 1.0.0 and 2.0.0). If you don't pass that in then the tool just behaves as it does currently and only merges unstable versions for the current stable version.

I may not have epxlained that very well!

**Comment by dazinator** [comment]
> That's the point where we (myself!) want to merge all previous unstable versions between the last stable release and the current stable release. At the moment, this won't work.

To extend that, I am having a hard time seeing why, when you do a merge using this tool, would you ever NOT want to merge all unstable versions since the last Stable version into the new Stable version. Just picking up a subset of unstable version that match the current stable version number seems like it will only continue to work reliably when you dont ever do any version bumping during development! But I admit perhaps my perspective is limited on this.

**Comment by GeertvanHorrik** [comment]
The `FromVersion` sounds really good. The reason I don't want to blindly merge is because we do several versions development at the same time. For example, we are working on:

1.0.0-beta5
1.1.0-unstable36

So while an app is in beta, a different team instantly starts working on vNext while the quality team fixes all bugs reported by the beta users. 

I think it would be good to make sure we check that all unstable versions we are merging are at least smaller or equal to the version being released (merged to).

**Comment by dazinator** [comment]
Agreed. Ok, so if I understand correctly we'd have to be careful to only merge "unstable" versions right?

So, given these versions:

| Version | Branch |
| --- | --- |
| 0.0.1-unstable01 | Dev |
| 0.0.1-unstable02 | Dev |
| 0.2.0-unstable01 | Dev |
| 1.0.0 | Master |
| 1.0.0-beta1 | Hotfix |
| 1.1.0-unstable01 | Dev |
| 1.1.0-unstable02 | Dev |
| 1.1.0 | Master |

When releasing `1.0.0` and supplying a `FromVersion` of `0.0.1` that would merge into 1.0.0:

0.0.1-unstable01
0.0.1-unstable02
0.2.0-unstable01

When releasing `1.1.0` and supplying a `FromVersion` of `1.0.0` that would merge into 1.1.0:
1.1.0-unstable01
1.1.0-unstable02

Does that sound about right to you?

We'd check that the `FromVersion` is in the format X.Y.Z i.e no label, and that it it less than or equal the version being merged into. 
We'd check (think we do already) that the version being merged into is a stable version number.

**Comment by dazinator** [comment]
Also quick question - can we assume SemVer version numbers, or does this tool have to cater for non semver version numbers too?

**Comment by GeertvanHorrik** [comment]
I am getting easier and easier with tools I / we write. We are the primary customers / users, so if we only use semver, yes, semver is the only thing we support :-)

**Comment by dazinator** [comment]
Ok excellent, that simplifies things a little bit.

**Comment by GeertvanHorrik** [comment]
About your versioning stuff:
1. Beta is not a hotfix, it's the release branch. Hotfix results in 1.0.1 versioning.

I think we can even get away without the `FromVersion` now I think about it a bit more. As long as we only merge (unstable) versions _before_ the current version being released, we can blindly merge. The only thing that we don't support (yet) in that case is that 0.2.0 and 0.3.0 get merged into a 1.0.0, but I think _if_ someone decides to release a 0.2.0, that should be considered a major version and never be merged.

**Comment by dazinator** [comment]
> Beta is not a hotfix, it's the release branch. Hotfix results in 1.0.1 versioning.

The reason I suggested Beta was for HotFix branches was because I took it from the GitVersion docs here: https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow/ and it says alpha is for Release branches!

We don't actually use most aspects of GitFlow yet, we are a small team of 4 and only have a development and a master branch so we are very simplified. We do occasionally do Feature branching, and our release branches only exist for a few minutes before they are merged. I suspect this may change in the future, once we have pushed a production release or if our roadmap becomes less linear.

> The only thing that we don't support (yet) in that case is that 0.2.0 and 0.3.0 get merged into a 1.0.0, but I think if someone decides to release a 0.2.0, that should be considered a major version and never be merged.

Yep. If someone decides to release a 0.2.0 then that would create a stable version 0.2.0 and all unstable versions less than that would be merged into it. As stable versions are not merged (only unstable versions are) then I can't necessarily see an issue here.

The only problem I see with taking away a FromVersion is that I wasn't sure sure whether you can assume that ALL unstable versions less than the current Stable version are candidates for the merge. But actually, perhaps we can assume that?

**Comment by GeertvanHorrik** [comment]
I think it's safe to make that assumption for now. Let's just do that and keep things simple for now.

**Comment by dazinator** [comment]
Cool. Happy for me to grab this one, or do you want to take it?

**Comment by GeertvanHorrik** [comment]
No please do, then I can fix some other things in the meantime

**Comment by dazinator** [comment]
Ok, making progress on this now.
